language: cpp

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

install:
    - sudo apt-get install libgtest-dev

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/:/usr/local/lib/
  - mkdir build && cd build
  - cmake ..
  - make tests

