language: cpp

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libgtest-dev

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir build && cd build
  - cmake ..
  - make tests

